name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Compilar o projeto
        run: mvn clean compile

      - name: Executar testes
        run: mvn test

      - name: Verificar o pacote
        run: mvn package