package org.example.academic.system.logging;

import org.example.academic.system.model.Role;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * TUS-2394 — log da geração de relatórios.
 */
public final class ReportAuditLogger {

    private static final Logger log = LoggerFactory.getLogger(ReportAuditLogger.class);

    private ReportAuditLogger() {}

    public static void generated(String reportName, Role role) {
        String r = (role == null) ? "UNKNOWN" : role.name();
        log.info("Report '{}' generated by role {}", reportName, r);
    }
}
